version: "2"
services:
  node:
    image: "node:8.6.0"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:  
      - "3000:3000"
    command: "npm start"